#!/bin/bash

ARGS=2
E_BADARGS=65
CONFIG_PATH=/etc/sysconfig/network-scripts

if [ $# -ne $ARGS ]  # Correct number of arguments passed to script?
then
    echo "Usage: `basename $0` <nic_name> <ovsbr_name>"
    exit $E_BADARGS
fi

bondnictobridge()
{
    nic=$1
    br=$2
    nic_file="${CONFIG_PATH}/ifcfg-${nic}"
    br_file="${CONFIG_PATH}/ifcfg-${br}"
    if ip addr show | grep -q $br; then
        echo "OVS Already Created!"
    else
        ip_addr=`ip addr show $nic | sed -nr 's/.*inet ([^ /]+).*/\1/p'`
        ip_prefix=`ip addr show $nic | sed -nr 's/.*inet .*\/([^ ]+).*/\1/p'`
        mac=`ip addr show $nic | sed -nr 's/.*ether ([^ ]+).*/\1/p' `
        gateway=`ip route list | sed -nr 's/default via ([^ ]+).*/\1/p'`
        echo "# Generated by parse-kickstart" > $nic_file
        echo "BOOTPROTO=none" >> $nic_file
        echo "DEVICE=$nic" >> $nic_file
        echo "ONBOOT=yes" >> $nic_file
        echo "HWADDR=$mac" >> $nic_file
        echo "TYPE=OVSPort" >> $nic_file
        echo "DEFROUTE=yes" >> $nic_file
        echo "DEVICETYPE=ovs" >> $nic_file
        echo "OVS_BRIDGE=$br" >> $nic_file
    
        echo "# Generated by parse-kickstart" > $br_file
        echo "BOOTPROTO=none" >> $br_file
        echo "DEVICE=$br" >> $br_file
        echo "ONBOOT=yes" >> $br_file
        echo "TYPE=OVSBridge" >> $br_file
        if [[ -n "$ip_addr"  ]] ; then
            echo "IPADDR0=$ip_addr" >> $br_file
            echo "PREFIX0=$ip_prefix" >> $br_file
        fi
        if [[ -n "$gateway"  ]] ; then 
            echo "GATEWAY0=$gateway" >> $br_file
        fi
        echo "DEFROUTE=yes" >> $br_file
        echo "DEVICETYPE=ovs" >> $br_file

        systemctl restart network.service
    fi

    if virsh net-list | grep -q "$br"; then
        exit 1
    else
        echo "<network>" > /tmp/ovsnet.xml
        echo "  <name>$br</name>" >> /tmp/ovsnet.xml
        echo "  <forward mode='bridge'/>" >> /tmp/ovsnet.xml
        echo "  <bridge name='$br'/>" >> /tmp/ovsnet.xml
        echo "  <virtualport type='openvswitch'/>" >> /tmp/ovsnet.xml
        echo "</network>" >> /tmp/ovsnet.xml

        virsh net-define /tmp/ovsnet.xml
        virsh net-start $br
        virsh net-autostart $br
    fi
}

# Bond Device to OVS
nic_name=$1
ovsbr_name=$2
bondnictobridge "$nic_name" "$ovsbr_name"

num="${ovsbr_name##${ovsbr_name%%?}}"  
ovs-vsctl set bridge $ovsbr_name external_ids:lc-br-id=$num
echo "ovs-vsctl set bridge $ovsbr_name external_ids:lc-br-id=$num" >> /etc/rc.local

echo Done
exit 0